### ISSUE TITLE
bump is weird

### ISSUE THREAD

**Issue by deodev** [BumpBotDiscord/implementations#1]
i tri bump but no work fix???!11!

**Comment by SlowestLoris** [comment]
I'm sorry, but this is the wrong location to post about your issues, please read the titles like everybody else.

**Comment by MisterCookiez** [comment]
1. Wrong repository. This should have been in the [bugs and suggestions repository](https://github.com/BumpBotDiscord/bugs-suggestions).
2. This is invalid.
